version: '3'

services:
    ofbiz:
      image:ofbiz
      volumes:
        - ./data:/ofbiz/runtime/data
        - ./config:/ofbiz/framework/entity/config/
      ports:
        - "8080:8080"
        - "8443:8443"

